book_outlet/urls.py
from django.urls import path
from .views import *

app_name = 'book_outlet'
urlpatterns = [
    path('new-book/', add_book, name='add_book'),
    path('new-address/', add_address, name='add_address'),
    path('new-country/', add_country, name='add_country'),
    path('new-author/', add_author, name='add_author'),
    path('', view_books, name='view_books'),
    path('<slug:slug>/', view_book, name='view_book'),
    path('delete/<int:id>', delete_book, name='delete_book'),
    path('edit/<int:id>', edit_book, name='edit_book'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('book_outlet.urls')),
]

book_outlet/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=80)
    code = models.CharField(max_length=2)

    def __str__(self):
        return f'{self.name} ({self.code})'

    class Meta:
        verbose_name_plural = 'countries'

class Address(models.Model):
    street = models.CharField(max_length=60)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.street} ({self.city})'

    class Meta:
        verbose_name_plural = 'Addresses'


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.OneToOneField(Address, on_delete=models.CASCADE, null=True)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.full_name()


class Book(models.Model):
    title  = models.CharField(max_length=70)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    author = models.ForeignKey(Author, on_delete= models.CASCADE, null=True)
    is_bestselling = models.BooleanField(default=False)
    published_countries = models.ManyToManyField(Country)
    slug = models.SlugField(default='', blank=True, null=False, editable=True)

    def get_absolute_url(self):
        return reverse('book_outlet:view_book', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title} ({self.rating})'

book_outlet/forms.py
from .models import *
from django.forms import ModelForm

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'rating', 'author', 'is_bestselling', 'published_countries']

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'address']


class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = ['street', 'postal_code', 'city']


class CountryForm(ModelForm):
    class Meta:
        model = Country
        fields = ['name', 'code']

book_outlet/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.db.models import Avg

# Create your views here.
def view_books(request):
    books = Book.objects.all().order_by('title')
    books_count = books.count()
    books_rating_avg = books.aggregate(Avg('rating'))
    context = {
        'books': books,
        'count': books_count,
        'rating_avg': books_rating_avg.get('rating__avg', 1)
    }
    return render(request, 'view_books.html', context)

def view_book(request, slug):
    try:
        book = Book.objects.get(slug=slug)
        context = {
            'book': book
        }
        return render(request, 'view_book.html', context)
    except:
        raise Http404()

def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book_outlet:view_books')
    else:
        form = BookForm()
    return render(request, 'add_book.html', {'form':form})

def delete_book(request, id):
    book = Book.objects.get(pk=id)
    book.delete()
    return HttpResponseRedirect(reverse('book_outlet:view_books'))

def edit_book(request, id):
    book = Book.objects.get(pk=id)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect(f'/books/{id}')
    else:
        form = BookForm(instance=book)

    return render(request, 'edit.html', {'form': form})


def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book_outlet:add_book')
    else:
        form = AuthorForm()
    return render(request, 'add_author.html', {'form': form})

def add_address(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book_outlet:add_book')
    else:
        form = AddressForm()
    return render(request, 'add_address.html', {'form':form})


def add_country(request):
    if request.method == 'POST':
        form = CountryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book_outlet:add_book')
    else:
        form = CountryForm()
    return render(request, 'add_country.html', {'form':form})

templates/add_address.html
{% extends 'base.html' %}

<title>
    {% block title %}
        Add address
    {% endblock title %}
</title>

{% block content %}
    <h1>New Address</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>
{% endblock content %}

templates/add_author.html
{% extends 'base.html' %}

<title>
    {% block title %}
        Add Author
    {% endblock title %}
</title>

{% block content %}
    <li><a href="{% url 'book_outlet:add_address' %}">Add Address</a></li>
    <h1>New Author</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>
{% endblock content %}

templates/add_book.html
{% extends 'base.html' %}

<title>
    {% block title %}
        New Book
    {% endblock title %}
</title>

{% block content %}
    <li><a href="{% url 'book_outlet:add_author' %}">Add Author</a></li>
    <li><a href="{% url 'book_outlet:add_country' %}">Add Country</a></li>
    <h1>New Book</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>
{% endblock content %}

templates/add_country.html
{% extends 'base.html' %}

<title>
    {% block title %}
        Add Country
    {% endblock title %}
</title>

{% block content %}
    <h1>New Country</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <title>{% block title %}Book Store{% endblock title %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'book_outlet:view_books' %}">All Books</a></li>
                <li><a href="{% url 'book_outlet:add_book' %}">Add Book</a></li>
                <li><a href="">Sign Up</a></li>
                <li><a href="">Log In</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/edit.html
{% extends 'base.html' %}

<title>
    {% block title %}
        Edit {{ book.title }}'s Book
    {% endblock title %}
</title>

{% block content %}
    <h1>Update Book</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>
{% endblock content %}

templates/view_book.html
{% extends 'base.html' %}

<title>
    {% block title %}
        {{ book.title }}'s Book
    {% endblock title %}
</title>

{% block content %}
    <h1>Book Detail</h1>
    <h3>Title: {{ book.title }}</h3>
    <h4>Rating: {{ book.rating }}</h4>
    <h4>Author: {{ book.author|title }}</h4>
    <h4>is best selling?
        {% if book.is_bestselling %}
            <span id="green">{{ book.is_bestselling }}</span>
        {% else %}
            <span id="red">{{ book.is_bestselling }}</span>
        {% endif %}
    </h4>
    <h4>Published countries:
        {% for country in book.published_countries.all %}
            {{ country }}
        {% endfor %}
    </h4>
    <a href="{% url 'book_outlet:delete_book' book.id %}">Delete</a>
    <a href="{% url 'book_outlet:edit_book' book.id %}">Edit</a>

{% endblock content %}

templates/view_books.html
{% extends 'base.html' %}

<title>
    {% block title %}
        All Books
    {% endblock title %}
</title>

{% block content %}
    <h1>All Books</h1>
    {% for book in books %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title|title }}</a></li>
    {% endfor %}
    <div class="infos">
        <p>Total books are: {{ count }} and average rating is: {{ rating_avg|floatformat:2 }}</p>
    </div>
{% endblock content %}